stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - deepfake_recognition/data_processing/data_download.py
    outs:
    - data/raw

  sampling_and_metadata:
    cmd: python -m deepfake_recognition/data_processing/data_sampling_and_metadata.py
    deps:
    - data/raw
    - deepfake_recognition/data_processing/data_sampling_and_metadata.py
    outs:
    - data/sampled_videos
    - data/metadata