stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - data_processing/data_download.py
    outs:
    - data/raw
  preprocess:
    cmd: python data_processing/data_preprocessing.py
    deps:
    - data/raw
    - data_processing/data_preprocessing.py
    outs:
    - data/metadata
  split:
    cmd: python data_processing/prepare_ffpp_split.py
    deps:
    - data/raw
    - data_processing/prepare_ffpp_split.py
    outs:
    - data/ffpp/train/fake
    - data/ffpp/train/real
    - data/ffpp/val/fake
    - data/ffpp/val/real
  process_for_VideoMAE:
    cmd: python data_processing/data_processing_for_VideoMAE.py
    deps:
    - data/ffpp/train/fake
    - data/ffpp/train/real
    - data/ffpp/val/fake
    - data/ffpp/val/real
    - data_processing/data_processing_for_VideoMAE.py
    outs:
    - data/ffpp_clips/test/fake
    - data/ffpp_clips/test/real
    - data/ffpp_clips/train/fake
    - data/ffpp_clips/train/real
    - data/ffpp_clips/val/fake
    - data/ffpp_clips/val/real
  sample:
    cmd: python data_processing/sample_dataset.py
    deps:
    - data/ffpp
    - data_processing/sample_dataset.py
    outs:
    - data/ffpp_sampled
