stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - deepfake_recognition/data_processing/data_download.py
    outs:
    - data/raw

  sampling_and_metadata:
    cmd: python deepfake_recognition/data_processing/data_sampling_and_metadata.py
    deps:
    - data/raw
    - deepfake_recognition/data_processing/data_sampling_and_metadata.py
    outs:
    - data/sampled_videos
    - data/metadata
  
  embedding_creation:
    cmd: python deepfake_recognition/data_processing/embedding_creation.py
    deps:
    - data/sampled_videos
    - deepfake_recognition/data_processing/embedding_creation.py
    outs:
    - data/embeddings

  lint:
    cmd: >
      pylint deepfake_recognition/ > reports/pylint_report.txt || true
    deps:
    - deepfake_recognition/
    outs:
    - reports/pylint_report.txt

  train:
    cmd: python deepfake_recognition/modeling/model_training.py
    deps:
    - deepfake_recognition/modeling/model_training.py
    - data/embeddings
    outs:
    - outputs/predictions.csv
    - outputs/model.joblib
    - emissions/emissions.csv