stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - deepfake_recognition/data_processing/data_download.py
    outs:
    - data/raw
    
  validate_raw:
    cmd: python deepfake_recognition/data_validation/validate_raw_data.py --data-dir data --min-per-class 1
    deps:
    - data/raw
    - deepfake_recognition/data_validation/validate_raw_data.py
    outs:
    - data/validation/raw_result.json

  sampling_and_metadata:
    cmd: python deepfake_recognition/data_processing/data_sampling_and_metadata.py
    deps:
    - data/raw
    - deepfake_recognition/data_processing/data_sampling_and_metadata.py
    outs:
    - data/sampled_videos
    - data/metadata
    
  validate_metadata:
    cmd: python deepfake_recognition/data_validation/validate_metadata.py --data-dir data
    deps:
    - data/metadata
    - deepfake_recognition/validation/validate_metadata.py
    outs:
    - data/validation/metadata_result.json
  
  embedding_creation:
    cmd: python deepfake_recognition/data_processing/embedding_creation.py
    deps:
    - data/sampled_videos
    - deepfake_recognition/data_processing/embedding_creation.py
    outs:
    - data/embeddings

  train:
    cmd: python deepfake_recognition/modeling/model_training.py
    deps:
    - deepfake_recognition/modeling/model_training.py
    - data/embeddings
    outs:
    - deepfake_recognition/modeling/logreg_model.pkl
    - deepfake_recognition/reports/emissions.csv
