stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - data_processing/data_download.py
    outs:
    - data/raw
  preprocess:
    cmd: python data_processing/data_preprocessing.py
    deps:
    - data/raw
    - data_processing/data_preprocessing.py
    outs:
    - data/metadata
  split:
    cmd: python data_processing/data_splitting.py
    deps:
    - data/metadata
    - data_processing/data_splitting.py
    outs:
    - data/processed
