stages:
  download:
    cmd: python data_processing/data_download.py --server EU2 -c c40 data/raw
    deps:
    - data_processing/data_download.py
    outs:
    - data/raw

  sample:
    cmd: python -m data_provisionals.data_sampling
    deps:
    - data/ffpp
    - data_provisionals/data_sampling.py
    outs:
    - data/ffpp_sampled

  preprocess:
    cmd: python -m data_processing.data_preprocessing
    deps:
    - data/raw
    - data_processing/data_preprocessing.py
    outs:
    - data/metadata